apiVersion: v1
kind: Service
metadata:
  name: product-inventory-service
spec:
  selector:
    app: product-inventory
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30083
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-inventory-deployment
spec:
  replicas: 1
  selector:
      matchLabels:
        app: product-inventory
  template:
    metadata:
      labels:
        app: product-inventory
    spec:
      containers:
        - name: product-inventory
          image: gcr.io/curious-ellipse-318103/ecommerce-product-inventory
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          env:
          # - name: MONGO_DATABASE
          #   valueFrom:
          #       configMapKeyRef:
          #           name: mongo-db-config
          #           key:  database
          # - name: MONGO_USERNAME
          #   valueFrom:
          #       secretKeyRef:
          #           name: mongo-db-secret
          #           key: pc-user1
          # - name: MONGO_PASSWORD
          #   valueFrom:
          #         secretKeyRef:
          #             name: mongo-db-secret
          #             key: pc-pwd1
            - name: MONGO_HOST
              valueFrom:
                  configMapKeyRef:
                      name: mongo-db-config
                      key:  pi-mongo-host
            - name: MONGO_PORT
              valueFrom:
                  configMapKeyRef:
                      name: mongo-db-config
                      key:  pi-mongo-port

          - name:  MONGODB_PRD_INV_URI
            # value: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DATABASE}
            value: mongodb://pi-mongo-0.pi-mongo, pi-mongo-1.pi-mongo, pi-mongo-2.pi-mongo/ecommerce
