apiVersion: v1
kind: Service
metadata:
  labels:
    app: product-inventory
    service: product-inventory
  name: product-inventory
  namespace: default
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: product-inventory
  type: ClusterIP
