apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: data-volume-pi-INST
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pi
  gcePersistentDisk:
    fsType: xfs
    pdName: pd-ssd-disk-pi-INST

