apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: data-volume-pc-INST
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pc
  gcePersistentDisk:
    fsType: xfs
    pdName: pd-ssd-disk-pc-INST

