apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pc-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---

apiVersion: v1
kind: Service
metadata:
  name: pc-mongo
spec:
  selector:
    app: pc-mongo
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 32463
      protocol: TCP
  type: NodePort
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pc-mongo
spec:
  selector:
    matchLabels:
      app: pc-mongo
  template:
    metadata:
      labels:
        app: pc-mongo
    spec:
      containers:
        - name: pc-mongo
          image: mongo
          ports:
            - containerPort: 27017
          env:
          - name: MONGO_INITDB_DATABASE
            valueFrom:
                configMapKeyRef:
                    name: mongo-db-config
                    key: init-db
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
                secretKeyRef:
                    name: mongo-db-secret
                    key: init-user
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
                secretKeyRef:
                    name: mongo-db-secret
                    key: init-password
          volumeMounts:
          - name: storage
            mountPath: /data/db
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: pc-mongo-pvc
