apiVersion: v1
kind: ConfigMap
metadata:
   name: mongo-db-config
data:
 pc-mongo-host: pc-mongo
 pc-mongo-port: "27017"
 pi-mongo-host: pi-mongo
 pi-mongo-port: "27019"
 pi-host: product-inventory-service
 pi-port: "8080"
 database: ecommerce
 init-db: admin


---

apiVersion: v1
kind: Secret
metadata:
      name: mongo-db-secret
type: Opaque
data:
      init-user: cm9vdA==
      init-password: cm9vdHJvb3Q=
      pc-user1: ZS11c2VyMQ==
      pc-pwd1: cHdkMQ==
      pi-user1: cC11c2VyMg==
      pi-pwd1: cHdkMg==
---
apiVersion: v1
kind: Service
metadata:
  name: pc-mongo
spec:
  selector:
    app: pc-mongo
  ports:
    - port: 27017
      targetPort: 27017
      # nodePort: 32463
      protocol: TCP
  clusterIP: None
  # type: NodePort
 
    
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pc-mongo
spec:
  selector:
    matchLabels:
      app: pc-mongo
  serviceName: pc-mongo
  replicas: 3
  template:
    metadata:
      labels:
        app: pc-mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: pc-mongo
          image: mongo
          command: 
          - mongod 
          - "--bind_ip_all"
          - "--replSet"
          - rs0
          ports:
            - containerPort: 27017
          env:
          - name: MONGO_INITDB_DATABASE
            valueFrom:
                configMapKeyRef:
                    name: mongo-db-config
                    key: init-db
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
                secretKeyRef:
                    name: mongo-db-secret
                    key: init-user
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
                secretKeyRef:
                    name: mongo-db-secret
                    key: init-password
          volumeMounts:
          - name: mongo-volume
            mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-volume
    spec:
      storageClassName: manual
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 200Mi

